[build]
  base = "frontend/"
  publish = "dist/frontend/browser/" # <--- CHANGE THIS LINE!
  command = "npm install && ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
