[build]
  base = "frontend/"
  publish = "frontend/dist/frontend/browser/"
  command = "npm install && ng build --configuration production" # Added npm install

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
